spring:
  application:
    name: backend-dev-service
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true

management:
    endpoints:
      web:
        exposure:
          include: "*"
terraform:
  dir: /home/hardik/terraform

jenkins:
  url: http://localhost:8080/job/deploy/build
  user: admin
  token: myjenkinstoken
